import assert from 'node:assert/strict';
import fs from 'node:fs';
import {JSDOM} from 'jsdom';

const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://example.org/index.html#frame-1',runScripts:'outside-only'});
const w=dom.window,d=w.document;
const jobs=new Map(),raf=new Map();let serial=0,hidden=false,now=0;
const reduced={matches:false,addEventListener(){}};
w.matchMedia=()=>reduced;
Object.defineProperty(d,'readyState',{value:'complete'});
Object.defineProperty(d,'hidden',{get:()=>hidden});
Object.defineProperty(d.documentElement,'scrollHeight',{value:6000});
w.setTimeout=(fn,delay)=>{assert.equal(delay,3000);jobs.set(++serial,fn);return serial;};
w.clearTimeout=id=>jobs.delete(id);
w.requestAnimationFrame=fn=>{raf.set(++serial,fn);return serial;};w.cancelAnimationFrame=id=>raf.delete(id);
w.scrollY=1000;d.body.style.setProperty('--story-phase','1');
const frames=[...d.querySelectorAll('.story-frame')];
frames.forEach((node,i)=>{node.getBoundingClientRect=()=>({top:i*1000+90-w.scrollY});});
d.querySelector('.portal-finale').getBoundingClientRect=()=>({top:4090-w.scrollY});
w.scrollTo=({top})=>{w.scrollY=top;d.body.style.setProperty('--story-phase',Math.min(3,top/1000));};
const tick=()=>{assert.equal(jobs.size,1);const [id,fn]=[...jobs][0];jobs.delete(id);fn();};
const step=delta=>{now+=delta;const pending=[...raf];raf.clear();pending.forEach(([,fn])=>fn(now));};
const finish=()=>{step(0);step(2400);};
const background=()=>d.body.dispatchEvent(new w.MouseEvent('click',{bubbles:true,clientX:200,clientY:200}));
w.eval(fs.readFileSync('portal-tour.js','utf8'));
const toggle=d.querySelector('[data-auto-tour]'),hint=d.querySelector('[data-portal-continue]');
assert.equal(toggle.getAttribute('aria-pressed'),'false');
toggle.click();
tick();assert.equal(w.scrollY,1000,'Timer starts a transition, not a jump');assert.equal(jobs.size,0);
step(0);step(600);assert.ok(w.scrollY>1100&&w.scrollY<1200,'Slow departure');
step(600);assert.ok(Math.abs(w.scrollY-1500)<1,'Continuous halfway pose');
step(1200);assert.equal(w.scrollY,2000);assert.equal(jobs.size,1,'Dwell starts after arrival');
background();assert.equal(toggle.getAttribute('aria-pressed'),'false');assert.ok(hint.disabled);
background();assert.equal(raf.size,1,'Repeated background clicks cannot skip multiple frames');
finish();assert.equal(w.scrollY,3000);assert.equal(jobs.size,0);assert.ok(!hint.disabled);
const previous=w.scrollY;w.museumPortalContainsPoint=()=>true;background();assert.equal(raf.size,0);assert.equal(w.scrollY,previous,'Wood rim is excluded');
w.museumPortalContainsPoint=()=>false;
toggle.click();hidden=true;d.dispatchEvent(new w.Event('visibilitychange'));assert.equal(jobs.size,0);
hidden=false;d.dispatchEvent(new w.Event('visibilitychange'));assert.equal(jobs.size,1);
w.scrollTo({top:1000});
w.eval(fs.readFileSync('portal-museum.js','utf8'));
const iframes=[...d.querySelectorAll('[data-exhibit-frame]')];
assert.deepEqual(iframes.map(f=>f.hasAttribute('src')),[false,true,true,false]);
iframes[1].contentDocument.open();iframes[1].contentDocument.write('<!doctype html><body>Artwork</body>');iframes[1].contentDocument.close();
iframes[1].dispatchEvent(new w.Event('load'));iframes[1].contentDocument.body.click();
assert.equal(jobs.size,0);assert.equal(raf.size,0);assert.equal(w.scrollY,1000,'Inside click stays on current painting');
hint.click();finish();assert.equal(w.scrollY,2000,'Hint also advances one painting');
background();step(0);step(600);w.dispatchEvent(new w.Event('wheel'));const stopped=w.scrollY;
step(2400);assert.equal(w.scrollY,stopped,'Manual scrolling cancels a transition');assert.equal(raf.size,0);
w.scrollTo({top:3000});toggle.click();tick();finish();assert.equal(w.scrollY,4000);assert.equal(jobs.size,0);
assert.equal(toggle.getAttribute('aria-pressed'),'false','Finale ends the tour');
reduced.matches=true;w.scrollTo({top:1000});hint.click();assert.equal(w.scrollY,2000);assert.equal(raf.size,0,'Reduced motion is immediate');
dom.window.close();
console.log('Passed: easing, dwell, background advance, repeat-click guard, rim exclusion, iframe takeover, wheel cancellation, hidden-page pause, finale, reduced motion.');
